name: Build Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

permissions:
  contents: read

jobs:
  windows:
    name: "Build Windows"
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: run-vcpkg
      uses: lukka/run-vcpkg@v10.2
      with:
        runVcpkgInstall: true
        vcpkgGitCommitId: 'e809a42f87565e803b2178a0c11263f462d1800a'
        
    - name: Integrate vcpkg
      run: vcpkg integrate install

    - name: Build Release
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:VcpkgEnableManifest=true /p:Configuration=Release
      
    - name: Build Debug
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:VcpkgEnableManifest=true /p:Configuration=Debug
      
    - uses: actions/upload-artifact@v3
      with:
        name: win64-release
        path: |
          x64/Release/SGDBop.exe
          x64/Release/libcurl.dll
          x64/Release/zlib1.dll

    - uses: actions/upload-artifact@v3
      with:
        name: win64-debug
        path: x64/Debug/*
  linux:
    name: "Build Linux"
    runs-on: ubuntu-latest
    env:
      OS: Linux

    steps:
    - uses: actions/checkout@v3

    - name: Install libcurl
      run: sudo apt-get install -y libcurl4-openssl-dev

    - name: Build
      run: make
      
    - uses: actions/upload-artifact@v3
      with:
        name: linux-build
        path: SGDBop

  release:
    if: github.event_name == 'release' && github.event.action == 'created'
    name: "Upload Artifacts"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [windows,linux]
    steps:
    - uses: actions/download-artifact@v3
      with:
        path: artifacts

    - name: Archive Windows Release Build
      run: 7z a sgdbop-win64.zip ./artifacts/win64-release/*

    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        omitName: true
        omitBody: true
        prerelease: true
        replacesArtifacts: true
        tag: ${{github.event.release.tag_name}}
        commit: ${{github.sha}}
        artifacts: "artifacts/linux-build/SGDBop,sgdbop-win64.zip"
